name: CICD using Maven and Tomcat

on:
  push:
  workflow_dispatch:

jobs:
  CICDjob:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repo on ubuntu server
        uses: actions/checkout@v4

      - name: Install Java and Maven on ubuntu server
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build the code
        run: mvn clean package

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Connect to Lab machine and trigger Jenkins job
        run: |
          sshpass -p '${{ secrets.SSH_PASS }}' ssh -o StrictHostKeyChecking=no labuser@15.206.1.117 << 'EOF'
            curl -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_PASS }} \
            http://localhost:8080/job/deployment-pipeline/build?token=token1
          EOF
